version: '2'

services:

  chamilo:
    restart: always
    build: ./dockerimage
    ports:
      - 8001:80
    volumes:
      - ./chamilo:/var/www/html/

  chamilo-mysql:
    restart: always
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: Standard1
      MYSQL_DATABASE: chamilo
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql/
